### ISSUE TITLE
Where are the VDI image ?

### ISSUE THREAD

**Issue by JOduMonT** [Taisun-Docker/taisun#11]
https://github.com/Taisun-Docker/taisun/wiki/VDI

### what I expect is what you showed
![image](https://user-images.githubusercontent.com/5204724/73413926-d5f7aa00-433f-11ea-9fc0-5abae14c8ab8.png)

### but instead it is what I've got
![image](https://user-images.githubusercontent.com/5204724/73413950-ef98f180-433f-11ea-83f3-377c96ee15dd.png)

**Comment by thelamer** [comment]
SInce that video was made multiple changes have been made to the VDI template. 
The most notable feature I dropped was the flavor concept with debian/ubuntu stuff.  

The current source for building these images can be found here: 
https://github.com/Taisun-Docker/vdi

With the old stuff based on VNC can be found here: 
https://gitlab.com/thelamer/taisun-vdi

Was their particular functionality you were specifically looking for ?

**Comment by JOduMonT** [comment]
> Was their particular functionality you were specifically looking for ?

I just want to run a GUI inside Docker as it showed
How I call this [Dockerfile](https://github.com/Taisun-Docker/vdi/blob/master/ubuntu/Dockerfile) from Taisun interface ?

**Comment by thelamer** [comment]
You just launch the VDI : 
![Peek 2020-01-29 19-20](https://user-images.githubusercontent.com/1852688/73417347-a065a900-42cc-11ea-87b1-aa72e57a76f9.gif)

The name is all the required information,

**Comment by JOduMonT** [comment]
it was too simple :)
thank for your quick help :+1:
