### ISSUE TITLE
Debian instead of Ubuntu

### ISSUE THREAD

**Issue by JOduMonT** [Taisun-Docker/taisun#3]
Hi;

in every demo I saw you choose debian, which would be my choice
but I simply have ubuntu bionic and xenial available.

I'm running linuxserver/taisun on OpenMediaVault 4 which is Debian 9

### How I could make debian available ?

![image](https://user-images.githubusercontent.com/5204724/57781626-dfe26a00-772a-11e9-95f7-f79c3523a8f3.png)

**Comment by thelamer** [comment]
Those videos are actually pretty outdated from a functionality standpoint. 

The reason Debian is no longer offered is because of my involvement with Linuxserver.io all of my images are based on their base images. (they only do Alpine and Ubuntu) 
To ensure these VDI images also work on other platforms like arm and arm64 I am only able to commit limited resources to testing them locally on my hardware. 
So I am unable at this time to also maintain a Debian base image with an S6 overlay to bring back the old Debian VDI images. 

I hope you understand, but I do have plans to add the same stack concept to the VDI images so the community can upload their own desktop variants or even just single GUI applications based on a new baseimage we have been working on at Linuxserver.io : 

https://github.com/linuxserver/docker-baseimage-guacgui

**Comment by JOduMonT** [comment]
@thelamer thanks for your quick and great answer.

> I hope you understand, ...

#### 1st: I was asking for Debian because I didn't truly understood the nature of the VDI and was expecting running OMV on top of it. I tough VDI was a kind of VM inside docker more or less like [this project](https://github.com/rancher/vm)

#### 2nd Now if someone don't understand this function is just totally awesome and works very well than focus on a specific distro instead of just using all this beauty, he don't deserve using your project ;)

## thank you so much for your works :+1:
