### ISSUE TITLE
Re-Think Development containers concept. 

### ISSUE THREAD

**Issue by knkrth** [Taisun-Docker/taisun#4]
Hi, Thanks for this project first of all. Is collaboration features of Cloud9 is still available in the latest taisun? Because as I can see in [wiki](https://github.com/Taisun-Docker/taisun/wiki/YourApp#cloud9) there will be a `set user` prompt will be displayed while launching Cloud9 but on the latest build it just directly get's into the IDE 

How can I enable collaboration features in Cloud9?

**Comment by thelamer** [comment]
No I killed that off and use a c9 core built specifically for Alpine linux with muslc. 
The modfications I made to the previous version can be seen here: 

https://github.com/thelamer/core/commit/ab79cfb769249d19e6d0443226a814a49dfabb36

This project has been solely developed by me as a side project, I am not sure there will ever be groups of developers working on it.

**Comment by knkrth** [comment]
Ok, I'll try to build my own c9sdk image with your commit later.

**Comment by melroy89** [comment]
What about [VS Code server](https://github.com/cdr/code-server) iso c9 (Cloud 9 is obsolete)?

Read more: https://github.com/cdr/code-server/issues/674

**Comment by melroy89** [comment]
Strange that its not part of the 'Stack' or something, since you do have your own Docker image already: https://hub.docker.com/r/linuxserver/code-server

**Comment by thelamer** [comment]
I think I misunderstand the issue ,  I thought we were talking about the cloud9 container this repo builds for developing Taisun (what I personally use) 

As far as the development containers launched by this template https://github.com/Taisun-Docker/taisun/blob/master/public/taisuntemplates/taisundeveloper.yml this concept existed before I ported the cloud9 concept into a Linuxserver.io container. (Even used to have a Desktop container option with a bunch of IDEs and programming envs installed but it was super heavy)
A key thing to keep in mind is I made this application before becoming a member of the Linuxserver.io team and many of the helper containers that came as Taisun features have since been fully ported to Linuxserver.io. 

This template can absolutely be modified to launch Code server, or even another recent port Pylon https://github.com/linuxserver/docker-pylon . But optimally the sub menu would just be ripped out and people would upload stacks for all this stuff (code server cloud9 etc etc) to https://stacks.taisun.io as this dedicated menu does not offer the advantages it once did now that it is using. 

I am going to re-title this issue and think about a more universal solution for people looking to launch dev stuff in Docker.

**Comment by thelamer** [comment]
I am gonna add the templates and launching for  code-server pylon and cloud9 also update the existing template to support auth variables. 
Sorry for the delay, focus was elsewhere for a bit, should be in the next release this week.

**Comment by knkrth** [comment]
Looking forward towards the next update.

**Comment by thelamer** [comment]
Pylon and Code-Server have been added to v0.5.0 just released.
