### ISSUE TITLE
Request features

### ISSUE THREAD

**Issue by knkrth** [Taisun-Docker/taisun#6]
Hi, Is it possible to provide feature like,

- Specifying `CPU core`, `RAM`  &
- Specifying `Disk storage size` while creating a container?
- Provide option to attach volume. 

Like other commercial cloud providers.

**Comment by thelamer** [comment]
The container creation stuff I really only made a skeleton because Portainer exists I even reference that in the Docs: 
https://github.com/Taisun-Docker/taisun/wiki/Images

In my view I would like people downstream to create stacks and upload them to https://stacks.taisun.io/ (many examples here). It could have any options you see fit, I tried to make the file format as friendly as possible and it plugs variables into compose: 
https://github.com/Taisun-Docker/taisun/wiki/Templates (need to use compose version 2 for ram cpu etc if you are copying examples) 

Even the container launcher is just a local stack definition: 

https://github.com/Taisun-Docker/taisun/blob/master/public/taisuntemplates/basetemplate.yml

**Comment by knkrth** [comment]
Ok, Thank you. Is there any plans to actively develop taisun?

**Comment by thelamer** [comment]
It does what I need it to do right now and as far as I know does not have any showstopping bugs, if there are features that fall in line with this projects intention (help a user with a single server manage it) I am all for adding them.

**Comment by knkrth** [comment]
With the help of auth we can manage the c9 with collaboration & add username & password to the usergroup based on the auth details. 

Like creating the c9 container with the username of the users. 

Is there any plan to provide a member management?

**Comment by thelamer** [comment]
I consume Cloud9 upstream https://github.com/linuxserver/docker-cloud9 (this consumes a now dead upstream repo https://github.com/c9/core) , now I am also the maintainer so it is not showstopping anything being under Linuxserver.io , but forking and maintaining the Cloud9 code base ever since they got bought by Amazon and no longer distro their source for plugin development as they do not exist as a platform is a hairy situation. 
Technically the project is not licensed for redistribution like this, Docker kind of skirts all those licensing issues . 

You need to understand that everything Taisun does is in Docker(there is zero local storage) , so there is no central Member management per say it does not even have auth. 
So what you are referring to for user management and using any of these containers (VDI, development, etc) is stuff that needs to be first integrated into those specific projects then variables can be introduced into the templates that are launching those docker containers.

**Comment by knkrth** [comment]
Ok, I got it.

**Comment by knkrth** [comment]
Have you considered https://github.com/pylonide/pylon it has [GPL v3](https://github.com/pylonide/pylon/blob/master/LICENSE) License

**Comment by thelamer** [comment]
Did not know that existed TBH, cool project though I will get that ported to Linuxserver

**Comment by knkrth** [comment]
😃 👍

**Comment by thelamer** [comment]
https://hub.docker.com/r/linuxserver/pylon FYI
It is only Alpine for now but going to see about creating some branches.
