### ISSUE TITLE
Docker resource management

### ISSUE THREAD

**Issue by knkrth** [Taisun-Docker/taisun#7]
Hi, Do u know how can we specify the resource management like specific CPU, RAM, DISK space for a container through `docker cli`?

**Comment by scottymyers** [comment]
I don't think you can actually change those thing.  I could be wrong, but the idea behind the docker is that it sits in closer to the OS, nuzzled up, so that it doesn't have the same RAM, CPU, and DISK limitations.  That said, I think there may be a way to CAP those on the docker service itself.  I don't know about individual containers running.  Again, I could be super wrong about this.

**Comment by knkrth** [comment]
Ok

**Comment by thelamer** [comment]
The run commands are here : 
https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources
The Compose reference is here: 
https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu-and-other-resources

With Taisun none of the templates I have currently created have this option: 
https://stacks.taisun.io

But anyone can upload stacks with those options available.
